[project]
name = "linmod"
version = "0.2.0"
description = ""
authors = [
    { name = "Thanasi Bakis", email = "abakis@uci.edu" },
    { name = "Andy Magee", email = "rzg0@cdc.gov" },
    { name = "Scott Olesen", email = "ulp7@cdc.gov" },
]
requires-python = ">=3.12,<3.13"
readme = "README.md"
dependencies = [
    "numpyro>=0.15.0",
    "numpy>=2.0.0,<3",
    "polars>=1.1.0,<2",
    "scipy>=1.14.0,<2",
    "zstandard>=0.22.0,<0.23",
    "plotnine",
    "pyarrow>=17.0.0,<18",
    "cladecombiner",
]

[dependency-groups]
dev = [
    "mdx-truly-sane-lists>=1.3",
    "mkdocstrings>=1.0.4",
    "mkdocstrings-python>=2.0.3",
    "pre-commit>=4.5.1",
    "pytest>=8.2.2,<9",
    "zensical>=0.0.35",
]

[tool.uv]

[tool.uv.sources]
cladecombiner = { git = "https://github.com/CDCGov/cladecombiner" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
