# Where are inputs and outputs stored?
paths:
  data: metadata.csv
  forecast_dir: out/
  scores: results.csv

# Which models should be fit?
models:
  - BaselineModel
  - IndependentDivisionsModel
  - HierarchicalDivisionsModel

# MCMC configuration
mcmc:
  warmup: 2500
  samples: 500
  chains: 4

# How many days since the forecast date should be included in the forecast?
forecast_horizon:
  lower: -30
  upper: 14

# How should forecasts be evaluated?
metrics:
  - proportions_mean_norm
  - proportions_energy_score
