data:
  # Where are the processed datasets for modeling and evaluation stored?
  save_file:
    model: data/metadata-model.csv
    eval: data/metadata-eval.csv

  # What is the forecast date?
  # No sequences collected or reported after this date are included in the
  # modeling dataset.
  forecast_date:
    year: 2020
    month: 10
    day: 1

  # How many days since the forecast date should be included in the datasets?
  # The evaluation dataset will contain sequences collected and reported within
  # this horizon. The modeling dataset will contain sequences collected and
  # reported within the horizon `[lower, 0]`.
  horizon:
    lower: -90
    upper: 14

forecasting:
  # Where (directory) should model output be stored?
  save_dir: out/

  # Which models should be fit?
  models:
    - BaselineModel
    - IndependentDivisionsModel
    - HierarchicalDivisionsModel

  # MCMC configuration
  mcmc:
    warmup: 2500
    samples: 500
    chains: 4

evaluation:
  # Where (file) should model scores be stored?
  save_file: results.csv

  # How should forecasts be evaluated?
  metrics:
    - proportions_mean_norm
    - proportions_energy_score
